const OFERTAS_EDUCATIVAS = [
  {
    id: 1,
    carrera: "Tec. Sup. en Enfermería",
    institucion: "Universidad Nacional del Comahue",
    localidad: "General Roca",
    lat: -39.0333,
    lng: -67.5833,
    zona: "Alto Valle",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Salud"
  },
  {
    id: 2,
    carrera: "Tec. Sup. en Radiología",
    institucion: "Universidad Nacional del Comahue",
    localidad: "General Roca",
    lat: -39.0333,
    lng: -67.5833,
    zona: "Alto Valle",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Salud"
  },
  {
    id: 3,
    carrera: "Tec. Sup. en Seguridad e Higiene en el Trabajo",
    institucion: "Centro de Capacitación Técnica",
    localidad: "General Roca",
    lat: -39.0333,
    lng: -67.5833,
    zona: "Alto Valle",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Industria"
  },
  {
    id: 4,
    carrera: "Prof. de Educación Primaria",
    institucion: "Universidad Nacional del Comahue",
    localidad: "Cipolletti",
    lat: -38.9339,
    lng: -67.9900,
    zona: "Alto Valle",
    tipo: "Grado",
    duracion: "4 años",
    modalidad: "Presencial",
    area: "Educación"
  },
  {
    id: 5,
    carrera: "Prof. de Educación Inicial",
    institucion: "Universidad Nacional del Comahue",
    localidad: "Cipolletti",
    lat: -38.9339,
    lng: -67.9900,
    zona: "Alto Valle",
    tipo: "Grado",
    duracion: "4 años",
    modalidad: "Presencial",
    area: "Educación"
  },
  {
    id: 6,
    carrera: "Tec. Sup. en Administración de Empresas",
    institucion: "Instituto Superior General Roca",
    localidad: "General Roca",
    lat: -39.0333,
    lng: -67.5833,
    zona: "Alto Valle",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Administración"
  },
  {
    id: 7,
    carrera: "Tec. Sup. en Gestión de los RRHH",
    institucion: "Instituto Superior General Roca",
    localidad: "General Roca",
    lat: -39.0333,
    lng: -67.5833,
    zona: "Alto Valle",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Administración"
  },
  {
    id: 8,
    carrera: "Tec. Sup. en Petróleo",
    institucion: "Instituto Superior General Roca",
    localidad: "General Roca",
    lat: -39.0333,
    lng: -67.5833,
    zona: "Alto Valle",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Minería"
  },
  {
    id: 9,
    carrera: "Tec. Sup. en Instrumentación Quirúrgica",
    institucion: "Universidad Nacional del Comahue",
    localidad: "General Roca",
    lat: -39.0333,
    lng: -67.5833,
    zona: "Alto Valle",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Salud"
  },
  {
    id: 10,
    carrera: "Tec. Sup. en Gastronomía",
    institucion: "Instituto Superior Viedma",
    localidad: "Viedma",
    lat: -40.8135,
    lng: -62.9967,
    zona: "Atlántica",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Turismo"
  },
  {
    id: 11,
    carrera: "Tec. Sup. en Turismo",
    institucion: "Instituto Superior Viedma",
    localidad: "Viedma",
    lat: -40.8135,
    lng: -62.9967,
    zona: "Atlántica",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Turismo"
  },
  {
    id: 12,
    carrera: "Tec. Sup. en Energías Renovables",
    institucion: "Universidad Nacional del Comahue",
    localidad: "Cipolletti",
    lat: -38.9339,
    lng: -67.9900,
    zona: "Alto Valle",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Industria"
  },
  {
    id: 13,
    carrera: "Tec. Sup. en Acompañamiento Terapéutico",
    institucion: "Instituto Superior General Roca",
    localidad: "General Roca",
    lat: -39.0333,
    lng: -67.5833,
    zona: "Alto Valle",
    tipo: "Tecnicatura",
    duracion: "2 años",
    modalidad: "Presencial",
    area: "Salud"
  },
  {
    id: 14,
    carrera: "Analista Multimedial en Marketing Digital",
    institucion: "Universidad de Flores",
    localidad: "General Roca",
    lat: -39.0333,
    lng: -67.5833,
    zona: "Alto Valle",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Virtual",
    area: "Tecnología"
  },
  {
    id: 15,
    carrera: "Tec. Sup. en Logística y Transporte",
    institucion: "Centro de Capacitación Técnica",
    localidad: "General Roca",
    lat: -39.0333,
    lng: -67.5833,
    zona: "Alto Valle",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Administración"
  },
  {
    id: 16,
    carrera: "Ingeniería en Petróleo",
    institucion: "Universidad Nacional del Comahue",
    localidad: "General Roca",
    lat: -39.0333,
    lng: -67.5833,
    zona: "Alto Valle",
    tipo: "Grado",
    duracion: "5 años",
    modalidad: "Presencial",
    area: "Minería"
  },
  {
    id: 17,
    carrera: "Lic. en Enfermería",
    institucion: "Universidad Nacional del Comahue",
    localidad: "Neuquén",
    lat: -38.9519,
    lng: -68.0585,
    zona: "Andina",
    tipo: "Grado",
    duracion: "4 años",
    modalidad: "Presencial",
    area: "Salud"
  },
  {
    id: 18,
    carrera: "Lic. en Medicina",
    institucion: "Universidad Nacional del Comahue",
    localidad: "Neuquén",
    lat: -38.9519,
    lng: -68.0585,
    zona: "Andina",
    tipo: "Grado",
    duracion: "6 años",
    modalidad: "Presencial",
    area: "Salud"
  },
  {
    id: 19,
    carrera: "Tec. Sup. en Construcción",
    institucion: "IUPA",
    localidad: "San Carlos de Bariloche",
    lat: -41.1335,
    lng: -71.3103,
    zona: "Andina",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Construcción"
  },
  {
    id: 20,
    carrera: "Lic. en Turismo",
    institucion: "IUPA",
    localidad: "San Carlos de Bariloche",
    lat: -41.1335,
    lng: -71.3103,
    zona: "Andina",
    tipo: "Grado",
    duracion: "4 años",
    modalidad: "Presencial",
    area: "Turismo"
  },
  {
    id: 21,
    carrera: "Tec. Sup. en Administración Agropecuaria",
    institucion: "Centro de Educación Agropecuaria",
    localidad: "General Roca",
    lat: -39.0333,
    lng: -67.5833,
    zona: "Alto Valle",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Agropecuario"
  },
  {
    id: 22,
    carrera: "Tec. Sup. en Electricidad Industrial",
    institucion: "Escuela de Aprendizaje de Oficios",
    localidad: "Viedma",
    lat: -40.8135,
    lng: -62.9967,
    zona: "Atlántica",
    tipo: "Tecnicatura",
    duracion: "2 años",
    modalidad: "Presencial",
    area: "Industria"
  },
  {
    id: 23,
    carrera: "Tec. Sup. en Seguridad e Higiene en el Trabajo",
    institucion: "ITS Choele Choel N°2",
    localidad: "Choele Choel",
    lat: -39.2833,
    lng: -65.6667,
    zona: "Valle Medio",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Industria"
  },
  {
    id: 24,
    carrera: "Tec. Sup. en Enfermería",
    institucion: "ITS Viedma N°1",
    localidad: "Viedma",
    lat: -40.8135,
    lng: -62.9967,
    zona: "Atlántica",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Salud"
  },
  {
    id: 25,
    carrera: "Tec. Sup. en Radiología",
    institucion: "ITS Viedma N°1",
    localidad: "Viedma",
    lat: -40.8135,
    lng: -62.9967,
    zona: "Atlántica",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Salud"
  },
  {
    id: 26,
    carrera: "Prof. de Educación Primaria",
    institucion: "UNRN",
    localidad: "San Carlos de Bariloche",
    lat: -41.1335,
    lng: -71.3103,
    zona: "Andina",
    tipo: "Grado",
    duracion: "4 años",
    modalidad: "Presencial",
    area: "Educación"
  },
  {
    id: 27,
    carrera: "Lic. en Psicología",
    institucion: "UNRN",
    localidad: "San Carlos de Bariloche",
    lat: -41.1335,
    lng: -71.3103,
    zona: "Andina",
    tipo: "Grado",
    duracion: "5 años",
    modalidad: "Presencial",
    area: "Salud"
  },
  {
    id: 28,
    carrera: "Tec. Sup. en Desarrollo de Software",
    institucion: "Instituto Superior Universe",
    localidad: "General Roca",
    lat: -39.0333,
    lng: -67.5833,
    zona: "Alto Valle",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Tecnología"
  },
  {
    id: 29,
    carrera: "Tec. Sup. en Redes y Comunicaciones",
    institucion: "Instituto Superior Universe",
    localidad: "General Roca",
    lat: -39.0333,
    lng: -67.5833,
    zona: "Alto Valle",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Tecnología"
  },
  {
    id: 30,
    carrera: "Lic. en Derecho",
    institucion: "UNRN",
    localidad: "Viedma",
    lat: -40.8135,
    lng: -62.9967,
    zona: "Atlántica",
    tipo: "Grado",
    duracion: "5 años",
    modalidad: "Presencial",
    area: "Derecho"
  },
  {
    id: 31,
    carrera: "Tec. Sup. en Hotelería",
    institucion: "IUPA",
    localidad: "San Carlos de Bariloche",
    lat: -41.1335,
    lng: -71.3103,
    zona: "Andina",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Turismo"
  },
  {
    id: 32,
    carrera: "Prof. de Matemática",
    institucion: "UNRN",
    localidad: "General Roca",
    lat: -39.0333,
    lng: -67.5833,
    zona: "Alto Valle",
    tipo: "Grado",
    duracion: "4 años",
    modalidad: "Presencial",
    area: "Educación"
  },
  {
    id: 33,
    carrera: "Lic. en Contaduría Pública",
    institucion: "Instituto Superior General Roca",
    localidad: "General Roca",
    lat: -39.0333,
    lng: -67.5833,
    zona: "Alto Valle",
    tipo: "Grado",
    duracion: "4 años",
    modalidad: "Presencial",
    area: "Administración"
  },
  {
    id: 34,
    carrera: "Tec. Sup. en Electricidad Industrial",
    institucion: "Escuela de Aprendizaje de Oficios",
    localidad: "General Roca",
    lat: -39.0333,
    lng: -67.5833,
    zona: "Alto Valle",
    tipo: "Tecnicatura",
    duracion: "2 años",
    modalidad: "Presencial",
    area: "Industria"
  },
  {
    id: 35,
    carrera: "Tec. Sup. en Mecánica Automotriz",
    institucion: "Escuela de Aprendizaje de Oficios",
    localidad: "General Roca",
    lat: -39.0333,
    lng: -67.5833,
    zona: "Alto Valle",
    tipo: "Tecnicatura",
    duracion: "2 años",
    modalidad: "Presencial",
    area: "Industria"
  },
  {
    id: 36,
    carrera: "Lic. en Arquitectura",
    institucion: "UNRN",
    localidad: "San Carlos de Bariloche",
    lat: -41.1335,
    lng: -71.3103,
    zona: "Andina",
    tipo: "Grado",
    duracion: "5 años",
    modalidad: "Presencial",
    area: "Construcción"
  },
  {
    id: 37,
    carrera: "Tec. Sup. en Diseño Gráfico",
    institucion: "IUPA",
    localidad: "San Carlos de Bariloche",
    lat: -41.1335,
    lng: -71.3103,
    zona: "Andina",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Arte y Diseño"
  },
  {
    id: 38,
    carrera: "Prof. de Inglés",
    institucion: "Instituto San Agustín",
    localidad: "General Roca",
    lat: -39.0333,
    lng: -67.5833,
    zona: "Alto Valle",
    tipo: "Grado",
    duracion: "4 años",
    modalidad: "Presencial",
    area: "Educación"
  },
  {
    id: 39,
    carrera: "Tec. Sup. en Comercialización",
    institucion: "ITS Cipolletti N°13",
    localidad: "Cipolletti",
    lat: -38.9339,
    lng: -67.9900,
    zona: "Alto Valle",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Administración"
  },
  {
    id: 40,
    carrera: "Lic. en Educación Física",
    institucion: "UNCO",
    localidad: "Neuquén",
    lat: -38.9519,
    lng: -68.0585,
    zona: "Andina",
    tipo: "Grado",
    duracion: "4 años",
    modalidad: "Presencial",
    area: "Educación"
  },
  {
    id: 41,
    carrera: "Tec. Sup. en Seguridad Minera",
    institucion: "Instituto Balseiro",
    localidad: "San Carlos de Bariloche",
    lat: -41.1335,
    lng: -71.3103,
    zona: "Andina",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Minería"
  },
  {
    id: 42,
    carrera: "Lic. en Física",
    institucion: "Instituto Balseiro",
    localidad: "San Carlos de Bariloche",
    lat: -41.1335,
    lng: -71.3103,
    zona: "Andina",
    tipo: "Grado",
    duracion: "5 años",
    modalidad: "Presencial",
    area: "Ciencias"
  },
  {
    id: 43,
    carrera: "Tec. Sup. en Producción Lechera",
    institucion: "Centro de Educación Agropecuaria",
    localidad: "General Roca",
    lat: -39.0333,
    lng: -67.5833,
    zona: "Alto Valle",
    tipo: "Tecnicatura",
    duracion: "2 años",
    modalidad: "Presencial",
    area: "Agropecuario"
  },
  {
    id: 44,
    carrera: "Prof. de Música",
    institucion: "Instituto Universitario Patagónico de las Artes",
    localidad: "Viedma",
    lat: -40.8135,
    lng: -62.9967,
    zona: "Atlántica",
    tipo: "Grado",
    duracion: "4 años",
    modalidad: "Presencial",
    area: "Arte y Diseño"
  },
  {
    id: 45,
    carrera: "Tec. Sup. en Enfermería",
    institucion: "ITS Ingeniero Jacobacci N°5",
    localidad: "Ingeniero Jacobacci",
    lat: -41.3333,
    lng: -69.5833,
    zona: "Estepa",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Salud"
  },
  {
    id: 46,
    carrera: "Tec. Sup. en Seguridad e Higiene",
    institucion: "ITS Los Menucos N°7",
    localidad: "Los Menucos",
    lat: -40.8500,
    lng: -69.0833,
    zona: "Estepa",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Industria"
  },
  {
    id: 47,
    carrera: "Tec. Sup. en Administración",
    institucion: "ITS Sierra Grande N°9",
    localidad: "Sierra Grande",
    lat: -41.1333,
    lng: -65.3500,
    zona: "Atlántica",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Administración"
  },
  {
    id: 48,
    carrera: "Lic. en Historia",
    institucion: "UNRN",
    localidad: "Viedma",
    lat: -40.8135,
    lng: -62.9967,
    zona: "Atlántica",
    tipo: "Grado",
    duracion: "4 años",
    modalidad: "Presencial",
    area: "Humanidades"
  },
  {
    id: 49,
    carrera: "Tec. Sup. en Recursos Naturales",
    institucion: "UNRN",
    localidad: "San Carlos de Bariloche",
    lat: -41.1335,
    lng: -71.3103,
    zona: "Andina",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Ambiente"
  },
  {
    id: 50,
    carrera: "Prof. de Educación Especial",
    institucion: "UNCO",
    localidad: "Neuquén",
    lat: -38.9519,
    lng: -68.0585,
    zona: "Andina",
    tipo: "Grado",
    duracion: "4 años",
    modalidad: "Presencial",
    area: "Educación"
  },
  {
    id: 51,
    carrera: "Tec. Sup. en Electrónica Industrial",
    institucion: "Escuela de Aprendizaje de Oficios",
    localidad: "Cipolletti",
    lat: -38.9339,
    lng: -67.9900,
    zona: "Alto Valle",
    tipo: "Tecnicatura",
    duracion: "2 años",
    modalidad: "Presencial",
    area: "Industria"
  },
  {
    id: 52,
    carrera: "Tec. Sup. en Toxicología",
    institucion: "Universidad Nacional del Comahue",
    localidad: "Neuquén",
    lat: -38.9519,
    lng: -68.0585,
    zona: "Andina",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Salud"
  },
  {
    id: 53,
    carrera: "Lic. en Comunicación Social",
    institucion: "UNRN",
    localidad: "General Roca",
    lat: -39.0333,
    lng: -67.5833,
    zona: "Alto Valle",
    tipo: "Grado",
    duracion: "4 años",
    modalidad: "Presencial",
    area: "Comunicación"
  },
  {
    id: 54,
    carrera: "Tec. Sup. en Seguridad Alimentaria",
    institucion: "Instituto Superior General Roca",
    localidad: "General Roca",
    lat: -39.0333,
    lng: -67.5833,
    zona: "Alto Valle",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Salud"
  },
  {
    id: 55,
    carrera: "Prof. de Ciencias Naturales",
    institucion: "UNRN",
    localidad: "Viedma",
    lat: -40.8135,
    lng: -62.9967,
    zona: "Atlántica",
    tipo: "Grado",
    duracion: "4 años",
    modalidad: "Presencial",
    area: "Educación"
  },
  {
    id: 56,
    carrera: "Tec. Sup. en Geología",
    institucion: "Instituto Balseiro",
    localidad: "San Carlos de Bariloche",
    lat: -41.1335,
    lng: -71.3103,
    zona: "Andina",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Ciencias"
  },
  {
    id: 57,
    carrera: "Lic. en Trabajo Social",
    institucion: "UNCO",
    localidad: "Neuquén",
    lat: -38.9519,
    lng: -68.0585,
    zona: "Andina",
    tipo: "Grado",
    duracion: "4 años",
    modalidad: "Presencial",
    area: "Ciencias Sociales"
  },
  {
    id: 58,
    carrera: "Tec. Sup. en Recursos Humanos",
    institucion: "ITS Cinco Saltos N°10",
    localidad: "Cinco Saltos",
    lat: -38.8167,
    lng: -68.0000,
    zona: "Alto Valle",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Administración"
  },
  {
    id: 59,
    carrera: "Tec. Sup. en Farmacia",
    institucion: "Universidad Nacional del Comahue",
    localidad: "Neuquén",
    lat: -38.9519,
    lng: -68.0585,
    zona: "Andina",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Salud"
  },
  {
    id: 60,
    carrera: "Lic. en Sociología",
    institucion: "UNRN",
    localidad: "General Roca",
    lat: -39.0333,
    lng: -67.5833,
    zona: "Alto Valle",
    tipo: "Grado",
    duracion: "4 años",
    modalidad: "Presencial",
    area: "Ciencias Sociales"
  },
  {
    id: 61,
    carrera: "Prof. de Filosofía",
    institucion: "UNRN",
    localidad: "Viedma",
    lat: -40.8135,
    lng: -62.9967,
    zona: "Atlántica",
    tipo: "Grado",
    duracion: "4 años",
    modalidad: "Presencial",
    area: "Humanidades"
  },
  {
    id: 62,
    carrera: "Tec. Sup. en Geomática",
    institucion: "Instituto Balseiro",
    localidad: "San Carlos de Bariloche",
    lat: -41.1335,
    lng: -71.3103,
    zona: "Andina",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Tecnología"
  },
  {
    id: 63,
    carrera: "Lic. en Ciencias Ambientales",
    institucion: "UNRN",
    localidad: "San Carlos de Bariloche",
    lat: -41.1335,
    lng: -71.3103,
    zona: "Andina",
    tipo: "Grado",
    duracion: "4 años",
    modalidad: "Presencial",
    area: "Ambiente"
  },
  {
    id: 64,
    carrera: "Tec. Sup. en Seguridad Patrimonial",
    institucion: "Escuela de Oficiales de la Policía de Río Negro",
    localidad: "Viedma",
    lat: -40.8135,
    lng: -62.9967,
    zona: "Atlántica",
    tipo: "Tecnicatura",
    duracion: "2 años",
    modalidad: "Presencial",
    area: "Seguridad"
  },
  {
    id: 65,
    carrera: "Prof. de Dibujo Técnico",
    institucion: "Instituto Superior General Roca",
    localidad: "General Roca",
    lat: -39.0333,
    lng: -67.5833,
    zona: "Alto Valle",
    tipo: "Grado",
    duracion: "4 años",
    modalidad: "Presencial",
    area: "Educación"
  },
  {
    id: 66,
    carrera: "Tec. Sup. en Electromedicina",
    institucion: "Universidad Nacional del Comahue",
    localidad: "General Roca",
    lat: -39.0333,
    lng: -67.5833,
    zona: "Alto Valle",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Salud"
  },
  {
    id: 67,
    carrera: "Lic. en Economía",
    institucion: "UNRN",
    localidad: "Viedma",
    lat: -40.8135,
    lng: -62.9967,
    zona: "Atlántica",
    tipo: "Grado",
    duracion: "4 años",
    modalidad: "Presencial",
    area: "Administración"
  },
  {
    id: 68,
    carrera: "Tec. Sup. en Minería",
    institucion: "Instituto Balseiro",
    localidad: "San Carlos de Bariloche",
    lat: -41.1335,
    lng: -71.3103,
    zona: "Andina",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Minería"
  },
  {
    id: 69,
    carrera: "Prof. de Biología",
    institucion: "UNRN",
    localidad: "General Roca",
    lat: -39.0333,
    lng: -67.5833,
    zona: "Alto Valle",
    tipo: "Grado",
    duracion: "4 años",
    modalidad: "Presencial",
    area: "Educación"
  },
  {
    id: 70,
    carrera: "Tec. Sup. en Química Industrial",
    institucion: "Instituto Superior General Roca",
    localidad: "General Roca",
    lat: -39.0333,
    lng: -67.5833,
    zona: "Alto Valle",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Industria"
  },
  {
    id: 71,
    carrera: "Lic. en Filosofía",
    institucion: "UNRN",
    localidad: "San Carlos de Bariloche",
    lat: -41.1335,
    lng: -71.3103,
    zona: "Andina",
    tipo: "Grado",
    duracion: "4 años",
    modalidad: "Presencial",
    area: "Humanidades"
  },
  {
    id: 72,
    carrera: "Tec. Sup. en Seguridad e Higiene",
    institucion: "ITS Catriel N°3",
    localidad: "Catriel",
    lat: -37.8750,
    lng: -67.7917,
    zona: "Alto Valle",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Industria"
  },
  {
    id: 73,
    carrera: "Prof. de Química",
    institucion: "UNCO",
    localidad: "Neuquén",
    lat: -38.9519,
    lng: -68.0585,
    zona: "Andina",
    tipo: "Grado",
    duracion: "4 años",
    modalidad: "Presencial",
    area: "Educación"
  },
  {
    id: 74,
    carrera: "Tec. Sup. en Diseño de Interiores",
    institucion: "IUPA",
    localidad: "San Carlos de Bariloche",
    lat: -41.1335,
    lng: -71.3103,
    zona: "Andina",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Arte y Diseño"
  },
  {
    id: 75,
    carrera: "Lic. en Arte",
    institucion: "IUPA",
    localidad: "Viedma",
    lat: -40.8135,
    lng: -62.9967,
    zona: "Atlántica",
    tipo: "Grado",
    duracion: "4 años",
    modalidad: "Presencial",
    area: "Arte y Diseño"
  },
  {
    id: 76,
    carrera: "Tec. Sup. en Procesamiento de Datos",
    institucion: "Instituto Superior Universe",
    localidad: "General Roca",
    lat: -39.0333,
    lng: -67.5833,
    zona: "Alto Valle",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Virtual",
    area: "Tecnología"
  },
  {
    id: 77,
    carrera: "Prof. de Educación Artística",
    institucion: "UNRN",
    localidad: "Viedma",
    lat: -40.8135,
    lng: -62.9967,
    zona: "Atlántica",
    tipo: "Grado",
    duracion: "4 años",
    modalidad: "Presencial",
    area: "Educación"
  },
  {
    id: 78,
    carrera: "Tec. Sup. en Mecánica Industrial",
    institucion: "Escuela de Aprendizaje de Oficios",
    localidad: "Viedma",
    lat: -40.8135,
    lng: -62.9967,
    zona: "Atlántica",
    tipo: "Tecnicatura",
    duracion: "2 años",
    modalidad: "Presencial",
    area: "Industria"
  },
  {
    id: 79,
    carrera: "Lic. en Turismo Sostenible",
    institucion: "Instituto Superior Viedma",
    localidad: "Viedma",
    lat: -40.8135,
    lng: -62.9967,
    zona: "Atlántica",
    tipo: "Grado",
    duracion: "4 años",
    modalidad: "Presencial",
    area: "Turismo"
  },
  {
    id: 80,
    carrera: "Tec. Sup. en Administración Rural",
    institucion: "Centro de Educación Agropecuaria",
    localidad: "Villa Regina",
    lat: -39.1000,
    lng: -67.0667,
    zona: "Alto Valle",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Agropecuario"
  },
  {
    id: 81,
    carrera: "Tec. Sup. en Seguridad e Higiene",
    institucion: "ITS Allen N°1",
    localidad: "Allen",
    lat: -38.9833,
    lng: -67.8333,
    zona: "Alto Valle",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Industria"
  },
  {
    id: 82,
    carrera: "Tec. Sup. en Enfermería",
    institucion: "ITS Villa Regina N°6",
    localidad: "Villa Regina",
    lat: -39.1000,
    lng: -67.0667,
    zona: "Alto Valle",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Salud"
  },
  {
    id: 83,
    carrera: "Prof. de Educación Física",
    institucion: "UNRN",
    localidad: "General Roca",
    lat: -39.0333,
    lng: -67.5833,
    zona: "Alto Valle",
    tipo: "Grado",
    duracion: "4 años",
    modalidad: "Presencial",
    area: "Educación"
  },
  {
    id: 84,
    carrera: "Tec. Sup. en Seguridad e Higiene",
    institucion: "ITS Cipolletti N°13",
    localidad: "Cipolletti",
    lat: -38.9339,
    lng: -67.9900,
    zona: "Alto Valle",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Industria"
  },
  {
    id: 85,
    carrera: "Lic. en Enfermería",
    institucion: "UNCO",
    localidad: "Neuquén",
    lat: -38.9519,
    lng: -68.0585,
    zona: "Andina",
    tipo: "Grado",
    duracion: "4 años",
    modalidad: "Presencial",
    area: "Salud"
  },
  {
    id: 86,
    carrera: "Tec. Sup. en Administración Pública",
    institucion: "IPAP",
    localidad: "Viedma",
    lat: -40.8135,
    lng: -62.9967,
    zona: "Atlántica",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Administración"
  },
  {
    id: 87,
    carrera: "Tec. Sup. en Seguridad e Higiene",
    institucion: "ITS San Antonio Oeste N°15",
    localidad: "San Antonio Oeste",
    lat: -40.7333,
    lng: -64.9500,
    zona: "Atlántica",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Industria"
  },
  {
    id: 88,
    carrera: "Prof. de Lengua y Literatura",
    institucion: "UNRN",
    localidad: "San Carlos de Bariloche",
    lat: -41.1335,
    lng: -71.3103,
    zona: "Andina",
    tipo: "Grado",
    duracion: "4 años",
    modalidad: "Presencial",
    area: "Educación"
  },
  {
    id: 89,
    carrera: "Tec. Sup. en Gastronomía",
    institucion: "Instituto Superior Patagónico",
    localidad: "San Carlos de Bariloche",
    lat: -41.1335,
    lng: -71.3103,
    zona: "Andina",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Turismo"
  },
  {
    id: 90,
    carrera: "Lic. en Psicopedagogía",
    institucion: "Instituto de Formación Superior Santa Ana",
    localidad: "General Roca",
    lat: -39.0333,
    lng: -67.5833,
    zona: "Alto Valle",
    tipo: "Grado",
    duracion: "4 años",
    modalidad: "Presencial",
    area: "Salud"
  },
  {
    id: 91,
    carrera: "Tec. Sup. en Enfermería",
    institucion: "Escuela Argentina de Estudios Superiores",
    localidad: "Cipolletti",
    lat: -38.9339,
    lng: -67.9900,
    zona: "Alto Valle",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Salud"
  },
  {
    id: 92,
    carrera: "Prof. de Informática",
    institucion: "Instituto Superior General Roca",
    localidad: "General Roca",
    lat: -39.0333,
    lng: -67.5833,
    zona: "Alto Valle",
    tipo: "Grado",
    duracion: "4 años",
    modalidad: "Presencial",
    area: "Tecnología"
  },
  {
    id: 93,
    carrera: "Tec. Sup. en Diseño Web",
    institucion: "Instituto Superior Universe",
    localidad: "General Roca",
    lat: -39.0333,
    lng: -67.5833,
    zona: "Alto Valle",
    tipo: "Tecnicatura",
    duracion: "2 años",
    modalidad: "Virtual",
    area: "Tecnología"
  },
  {
    id: 94,
    carrera: "Lic. en Kinesiología y Fisiatría",
    institucion: "UNCO",
    localidad: "Neuquén",
    lat: -38.9519,
    lng: -68.0585,
    zona: "Andina",
    tipo: "Grado",
    duracion: "4 años",
    modalidad: "Presencial",
    area: "Salud"
  },
  {
    id: 95,
    carrera: "Tec. Sup. en Seguridad e Higiene",
    institucion: "Aulas Talleres Móviles",
    localidad: "Itinerante",
    lat: -39.5000,
    lng: -67.0000,
    zona: "Varios",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Industria"
  },
  {
    id: 96,
    carrera: "Prof. de Geografía",
    institucion: "UNRN",
    localidad: "Viedma",
    lat: -40.8135,
    lng: -62.9967,
    zona: "Atlántica",
    tipo: "Grado",
    duracion: "4 años",
    modalidad: "Presencial",
    area: "Educación"
  },
  {
    id: 97,
    carrera: "Tec. Sup. en Instrumentación Quirúrgica",
    institucion: "ISSAG",
    localidad: "General Roca",
    lat: -39.0333,
    lng: -67.5833,
    zona: "Alto Valle",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Salud"
  },
  {
    id: 98,
    carrera: "Lic. en Fonoaudiología",
    institucion: "Universidad Nacional del Comahue",
    localidad: "Neuquén",
    lat: -38.9519,
    lng: -68.0585,
    zona: "Andina",
    tipo: "Grado",
    duracion: "4 años",
    modalidad: "Presencial",
    area: "Salud"
  },
  {
    id: 99,
    carrera: "Tec. Sup. en Administración de Empresas",
    institucion: "Instituto Superior Viedma",
    localidad: "Viedma",
    lat: -40.8135,
    lng: -62.9967,
    zona: "Atlántica",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Administración"
  },
  {
    id: 100,
    carrera: "Prof. de Educación Física",
    institucion: "ITS Choele Choel N°2",
    localidad: "Choele Choel",
    lat: -39.2833,
    lng: -65.6667,
    zona: "Valle Medio",
    tipo: "Grado",
    duracion: "4 años",
    modalidad: "Presencial",
    area: "Educación"
  },
  // Carreras para Valcheta
  {
    id: 101,
    carrera: "Tec. Sup. en Enfermería",
    institucion: "ITS Valcheta N°8",
    localidad: "Valcheta",
    lat: -40.7167,
    lng: -66.1667,
    zona: "Estepa",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Salud"
  },
  {
    id: 102,
    carrera: "Tec. Sup. en Administración",
    institucion: "ITS Valcheta N°8",
    localidad: "Valcheta",
    lat: -40.7167,
    lng: -66.1667,
    zona: "Estepa",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Administración"
  },
  {
    id: 103,
    carrera: "Tec. Sup. en Seguridad e Higiene",
    institucion: "ITS Valcheta N°8",
    localidad: "Valcheta",
    lat: -40.7167,
    lng: -66.1667,
    zona: "Estepa",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Industria"
  },
  // Carreras para Ingeniero Jacobacci
  {
    id: 104,
    carrera: "Tec. Sup. en Enfermería",
    institucion: "ITS Ingeniero Jacobacci N°5",
    localidad: "Ingeniero Jacobacci",
    lat: -41.3333,
    lng: -69.5833,
    zona: "Estepa",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Salud"
  },
  {
    id: 105,
    carrera: "Tec. Sup. en Administración",
    institucion: "ITS Ingeniero Jacobacci N°5",
    localidad: "Ingeniero Jacobacci",
    lat: -41.3333,
    lng: -69.5833,
    zona: "Estepa",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Administración"
  },
  {
    id: 106,
    carrera: "Tec. Sup. en Petróleo",
    institucion: "ITS Ingeniero Jacobacci N°5",
    localidad: "Ingeniero Jacobacci",
    lat: -41.3333,
    lng: -69.5833,
    zona: "Estepa",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Minería"
  },
  // Carreras para Los Menucos
  {
    id: 107,
    carrera: "Tec. Sup. en Enfermería",
    institucion: "ITS Los Menucos N°7",
    localidad: "Los Menucos",
    lat: -40.8500,
    lng: -69.0833,
    zona: "Estepa",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Salud"
  },
  {
    id: 108,
    carrera: "Tec. Sup. en Administración",
    institucion: "ITS Los Menucos N°7",
    localidad: "Los Menucos",
    lat: -40.8500,
    lng: -69.0833,
    zona: "Estepa",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Administración"
  },
  {
    id: 109,
    carrera: "Tec. Sup. en Seguridad e Higiene",
    institucion: "ITS Los Menucos N°7",
    localidad: "Los Menucos",
    lat: -40.8500,
    lng: -69.0833,
    zona: "Estepa",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Industria"
  },
  // Carreras para Sierra Grande
  {
    id: 110,
    carrera: "Tec. Sup. en Enfermería",
    institucion: "ITS Sierra Grande N°9",
    localidad: "Sierra Grande",
    lat: -41.1333,
    lng: -65.3500,
    zona: "Atlántica",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Salud"
  },
  {
    id: 111,
    carrera: "Tec. Sup. en Administración",
    institucion: "ITS Sierra Grande N°9",
    localidad: "Sierra Grande",
    lat: -41.1333,
    lng: -65.3500,
    zona: "Atlántica",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Administración"
  },
  {
    id: 112,
    carrera: "Tec. Sup. en Minas",
    institucion: "ITS Sierra Grande N°9",
    localidad: "Sierra Grande",
    lat: -41.1333,
    lng: -65.3500,
    zona: "Atlántica",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Minería"
  },
  // Carreras para Catriel
  {
    id: 113,
    carrera: "Tec. Sup. en Enfermería",
    institucion: "ITS Catriel N°3",
    localidad: "Catriel",
    lat: -37.8750,
    lng: -67.7917,
    zona: "Alto Valle",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Salud"
  },
  {
    id: 114,
    carrera: "Tec. Sup. en Petróleo",
    institucion: "ITS Catriel N°3",
    localidad: "Catriel",
    lat: -37.8750,
    lng: -67.7917,
    zona: "Alto Valle",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Minería"
  },
  {
    id: 115,
    carrera: "Tec. Sup. en Administración",
    institucion: "ITS Catriel N°3",
    localidad: "Catriel",
    lat: -37.8750,
    lng: -67.7917,
    zona: "Alto Valle",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Administración"
  },
  // Carreras para Cinco Saltos
  {
    id: 116,
    carrera: "Tec. Sup. en Enfermería",
    institucion: "ITS Cinco Saltos N°10",
    localidad: "Cinco Saltos",
    lat: -38.8167,
    lng: -68.0000,
    zona: "Alto Valle",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Salud"
  },
  {
    id: 117,
    carrera: "Tec. Sup. en Administración",
    institucion: "ITS Cinco Saltos N°10",
    localidad: "Cinco Saltos",
    lat: -38.8167,
    lng: -68.0000,
    zona: "Alto Valle",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Administración"
  },
  {
    id: 118,
    carrera: "Tec. Sup. en Recursos Humanos",
    institucion: "ITS Cinco Saltos N°10",
    localidad: "Cinco Saltos",
    lat: -38.8167,
    lng: -68.0000,
    zona: "Alto Valle",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Administración"
  },
  // Carreras para Choele Choel
  {
    id: 119,
    carrera: "Tec. Sup. en Enfermería",
    institucion: "ITS Choele Choel N°2",
    localidad: "Choele Choel",
    lat: -39.2833,
    lng: -65.6667,
    zona: "Valle Medio",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Salud"
  },
  {
    id: 120,
    carrera: "Tec. Sup. en Administración",
    institucion: "ITS Choele Choel N°2",
    localidad: "Choele Choel",
    lat: -39.2833,
    lng: -65.6667,
    zona: "Valle Medio",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Administración"
  },
  // Carreras para Allen
  {
    id: 121,
    carrera: "Tec. Sup. en Enfermería",
    institucion: "ITS Allen N°1",
    localidad: "Allen",
    lat: -38.9833,
    lng: -67.8333,
    zona: "Alto Valle",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Salud"
  },
  {
    id: 122,
    carrera: "Tec. Sup. en Administración",
    institucion: "ITS Allen N°1",
    localidad: "Allen",
    lat: -38.9833,
    lng: -67.8333,
    zona: "Alto Valle",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Administración"
  },
  // Carreras para Villa Regina
  {
    id: 123,
    carrera: "Tec. Sup. en Enfermería",
    institucion: "ITS Villa Regina N°6",
    localidad: "Villa Regina",
    lat: -39.1000,
    lng: -67.0667,
    zona: "Alto Valle",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Salud"
  },
  {
    id: 124,
    carrera: "Tec. Sup. en Administración",
    institucion: "ITS Villa Regina N°6",
    localidad: "Villa Regina",
    lat: -39.1000,
    lng: -67.0667,
    zona: "Alto Valle",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Administración"
  },
  {
    id: 125,
    carrera: "Tec. Sup. en Turismo",
    institucion: "ITS Villa Regina N°6",
    localidad: "Villa Regina",
    lat: -39.1000,
    lng: -67.0667,
    zona: "Alto Valle",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Turismo"
  },
  // Carreras para San Antonio Oeste
  {
    id: 126,
    carrera: "Tec. Sup. en Enfermería",
    institucion: "ITS San Antonio Oeste N°15",
    localidad: "San Antonio Oeste",
    lat: -40.7333,
    lng: -64.9500,
    zona: "Atlántica",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Salud"
  },
  {
    id: 127,
    carrera: "Tec. Sup. en Administración",
    institucion: "ITS San Antonio Oeste N°15",
    localidad: "San Antonio Oeste",
    lat: -40.7333,
    lng: -64.9500,
    zona: "Atlántica",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Administración"
  },
  {
    id: 128,
    carrera: "Tec. Sup. en Turismo",
    institucion: "ITS San Antonio Oeste N°15",
    localidad: "San Antonio Oeste",
    lat: -40.7333,
    lng: -64.9500,
    zona: "Atlántica",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Turismo"
  },
  // Carreras para Río Colorado
  {
    id: 129,
    carrera: "Tec. Sup. en Enfermería",
    institucion: "IFDC Río Colorado",
    localidad: "Río Colorado",
    lat: -39.0167,
    lng: -64.0833,
    zona: "Valle Medio",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Salud"
  },
  {
    id: 130,
    carrera: "Tec. Sup. en Administración",
    institucion: "IFDC Río Colorado",
    localidad: "Río Colorado",
    lat: -39.0167,
    lng: -64.0833,
    zona: "Valle Medio",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Administración"
  },
  // Carreras para Lamarque
  {
    id: 131,
    carrera: "Tec. Sup. en Enfermería",
    institucion: "Lamarque Local",
    localidad: "Lamarque",
    lat: -39.1000,
    lng: -66.6833,
    zona: "Valle Medio",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Salud"
  },
  {
    id: 132,
    carrera: "Tec. Sup. en Administración",
    institucion: "Lamarque Local",
    localidad: "Lamarque",
    lat: -39.1000,
    lng: -66.6833,
    zona: "Valle Medio",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Administración"
  },
  // Carreras para Las Grutas
  {
    id: 133,
    carrera: "Tec. Sup. en Turismo",
    institucion: "Las Grutas Local",
    localidad: "Las Grutas",
    lat: -40.8000,
    lng: -65.0833,
    zona: "Atlántica",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Turismo"
  },
  {
    id: 134,
    carrera: "Tec. Sup. en Gastronomía",
    institucion: "Las Grutas Local",
    localidad: "Las Grutas",
    lat: -40.8000,
    lng: -65.0833,
    zona: "Atlántica",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Turismo"
  },
  // Carreras para General Conesa
  {
    id: 135,
    carrera: "Tec. Sup. en Enfermería",
    institucion: "General Conesa Local",
    localidad: "General Conesa",
    lat: -40.5833,
    lng: -64.4667,
    zona: "Valle Medio",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Salud"
  },
  {
    id: 136,
    carrera: "Tec. Sup. en Administración",
    institucion: "General Conesa Local",
    localidad: "General Conesa",
    lat: -40.5833,
    lng: -64.4667,
    zona: "Valle Medio",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Administración"
  },
  // Carreras para Maquinchao
  {
    id: 137,
    carrera: "Tec. Sup. en Enfermería",
    institucion: "Maquinchao Local",
    localidad: "Maquinchao",
    lat: -41.2500,
    lng: -68.7500,
    zona: "Estepa",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Salud"
  },
  {
    id: 138,
    carrera: "Tec. Sup. en Administración",
    institucion: "Maquinchao Local",
    localidad: "Maquinchao",
    lat: -41.2500,
    lng: -68.7500,
    zona: "Estepa",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Administración"
  },
  // Carreras para Chimpay
  {
    id: 139,
    carrera: "Tec. Sup. en Enfermería",
    institucion: "Chimpay Local",
    localidad: "Chimpay",
    lat: -39.1667,
    lng: -66.1833,
    zona: "Valle Medio",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Salud"
  },
  {
    id: 140,
    carrera: "Tec. Sup. en Administración",
    institucion: "Chimpay Local",
    localidad: "Chimpay",
    lat: -39.1667,
    lng: -66.1833,
    zona: "Valle Medio",
    tipo: "Tecnicatura",
    duracion: "3 años",
    modalidad: "Presencial",
    area: "Administración"
  }
];

// Tipos de formación disponibles
const TIPOS_FORMACION = [
  { nombre: "Tecnicatura", color: "#6ac64f", cantidad: 262 },
  { nombre: "Grado", color: "#007be0", cantidad: 190 },
  { nombre: "Formación Profesional", color: "#6ac64f", cantidad: 141 },
  { nombre: "Ciclo Complementario", color: "#007be0", cantidad: 21 },
  { nombre: "Posgrado", color: "#c9721b", cantidad: 19 },
  { nombre: "Pre-grado", color: "#6a4fb0", cantidad: 16 },
  { nombre: "Diplomatura", color: "#c9721b", cantidad: 2 }
];

// Áreas temáticas
const AREAS_TEMATICAS = [
  { nombre: "Salud", icono: "🏥", cantidad: 108 },
  { nombre: "Construcción e Industria", icono: "🏗️", cantidad: 106 },
  { nombre: "Educación", icono: "📚", cantidad: 94 },
  { nombre: "Administración", icono: "💼", cantidad: 68 },
  { nombre: "Turismo y Gastronomía", icono: "✈️", cantidad: 46 },
  { nombre: "Arte y Diseño", icono: "🎨", cantidad: 37 },
  { nombre: "Minería y Energía", icono: "⚡", cantidad: 32 },
  { nombre: "Tecnología e Informática", icono: "💻", cantidad: 30 },
  { nombre: "Humanidades", icono: "📖", cantidad: 28 },
  { nombre: "Agropecuario", icono: "🌾", cantidad: 24 },
  { nombre: "Ambiente", icono: "🌿", cantidad: 21 },
  { nombre: "Comunicación", icono: "📺", cantidad: 21 },
  { nombre: "Seguridad", icono: "🛡️", cantidad: 12 },
  { nombre: "Deportes", icono: "⚽", cantidad: 11 },
  { nombre: "Derecho", icono: "⚖️", cantidad: 10 }
];
